spring.application.name=financeia-backend

spring.config.import=optional:file:../../.env

# H2 Configuration
spring.datasource.url=jdbc:h2:file:./data/financeia_db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Initialize schema from root database_schema.sql
spring.sql.init.mode=never

# We disable flyway for now so we can use the strict schema
spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT secret from .env
jwt.secret=${JWT_SECRET}

# Integracion Backend -> Data Science
financeai.python.command=${PYTHON_COMMAND:../../financeai-data-science/.venv/Scripts/python.exe}
financeai.data-science.script=${DATA_SCIENCE_SCRIPT:../../financeai-data-science/src/predict.py}

