spring.application.name=financeia-backend

# Conexion local con H2 para pruebas
spring.datasource.url=jdbc:h2:mem:financeia_db
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.flywaydb=DEBUG

# Clave de firma JWT configurada mediante variable de entorno
jwt.secret=${JWT_SECRET}